"""add_feed_cache_table

Revision ID: 046d2381ff7b
Revises: e2aa025c4284
Create Date: 2026-06-06 10:40:00.978473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '046d2381ff7b'
down_revision: Union[str, Sequence[str], None] = 'e2aa025c4284'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed_caches',
    sa.Column('feed_id', sa.String(), nullable=False),
    sa.Column('etag', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('feed_id')
    )
    op.create_index(op.f('ix_feed_caches_feed_id'), 'feed_caches', ['feed_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feed_caches_feed_id'), table_name='feed_caches')
    op.drop_table('feed_caches')
    # ### end Alembic commands ###
