"""Add index to received_at

Revision ID: 74259bd2ac33
Revises: 75ed3dbf1e16
Create Date: 2026-04-19 18:34:57.999801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74259bd2ac33'
down_revision: Union[str, Sequence[str], None] = '75ed3dbf1e16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_entries_newsletter_id_received_at', 'entries', ['newsletter_id', 'received_at'], unique=False)
    op.create_index(op.f('ix_entries_received_at'), 'entries', ['received_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entries_received_at'), table_name='entries')
    op.drop_index('ix_entries_newsletter_id_received_at', table_name='entries')
    # ### end Alembic commands ###
