"""remove_globally_unique_message_id

Revision ID: 94c168d7c633
Revises: ae901c18e2e3
Create Date: 2026-07-13 18:17:14.241598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94c168d7c633'
down_revision: Union[str, Sequence[str], None] = 'ae901c18e2e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries') as batch_op:
        batch_op.drop_index('ix_entries_message_id')
        batch_op.create_index('ix_entries_message_id', ['message_id'], unique=False)
        batch_op.create_unique_constraint('uq_entry_message_newsletter', ['message_id', 'newsletter_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries') as batch_op:
        batch_op.drop_constraint('uq_entry_message_newsletter', type_='unique')
        batch_op.drop_index('ix_entries_message_id')
        batch_op.create_index('ix_entries_message_id', ['message_id'], unique=True)
    # ### end Alembic commands ###
