"""remove_globally_unique_sender

Revision ID: ae901c18e2e3
Revises: 046d2381ff7b
Create Date: 2026-07-13 18:16:49.493023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae901c18e2e3'
down_revision: Union[str, Sequence[str], None] = '046d2381ff7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('senders') as batch_op:
        batch_op.drop_index('ix_senders_email')
        batch_op.create_index('ix_senders_email', ['email'], unique=False)
        batch_op.create_unique_constraint('uq_sender_email_newsletter', ['email', 'newsletter_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('senders') as batch_op:
        batch_op.drop_constraint('uq_sender_email_newsletter', type_='unique')
        batch_op.drop_index('ix_senders_email')
        batch_op.create_index('ix_senders_email', ['email'], unique=True)
    # ### end Alembic commands ###
