"""add_master_feed_token

Revision ID: e2aa025c4284
Revises: 74259bd2ac33
Create Date: 2026-05-21 20:37:48.501600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2aa025c4284'
down_revision: Union[str, Sequence[str], None] = '74259bd2ac33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('master_feed_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'master_feed_token')
    # ### end Alembic commands ###
